Hastane/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Hastane.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using Hastane.Models;
using NETCore.Encrypt.Extensions;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;



// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Hastane.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _databaseContext;

        public AdminController(ApplicationDbContext databaseContext)
        {
            _databaseContext = databaseContext;

        }
        public IActionResult Index()
        {
            var anaBilimDallari = _databaseContext.AnaBilimDallari.ToList();
            return View(anaBilimDallari);
        }
        public IActionResult YeniAnaBilimDali()
        {

            return View();
        }
        [HttpPost]
        public IActionResult YeniAnaBilimDali(AnaBilimDali yeniDal)
        {
            _databaseContext.Add(yeniDal);
            _databaseContext.SaveChanges();
            return RedirectToAction("index");
        }

        public IActionResult AnaBilimDaliSil(Guid id)
        {
            var silinecek = _databaseContext.AnaBilimDallari.FirstOrDefault(abd => abd.Id == id);

            _databaseContext.AnaBilimDallari.Remove(silinecek);
            _databaseContext.SaveChanges();
            return RedirectToAction("index");
        }


        public IActionResult AnaBilimDaliGetir(Guid id)
        {
            var dal = _databaseContext.AnaBilimDallari.FirstOrDefault(abd => abd.Id == id);

            return View(dal);
        }
        public IActionResult AnaBilimDaliGuncelle(AnaBilimDali anaBilim)
        {
            var dal = _databaseContext.AnaBilimDallari.FirstOrDefault(abd => abd.Id == anaBilim.Id);

            dal.Name = anaBilim.Name;
            _databaseContext.SaveChanges();
            return RedirectToAction("index");
        }

        public IActionResult PoliklinikIndex()
        {
            var poliklinikler = _databaseContext.Poliklinikler.Include(x => x.AnaBilimDali).ToList();
            return View(poliklinikler);
        }

        public IActionResult YeniPoliklinik()
        {

            List<SelectListItem> dallar = (from x in _databaseContext.AnaBilimDallari.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Name,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.dgr = dallar;
            return View();
        }
        [HttpPost]
        public IActionResult YeniPoliklinik(Poliklinik p)
        {
            var existingPoliklinik = _databaseContext.Poliklinikler.FirstOrDefault(x => x.Name == p.Name);

            if (existingPoliklinik != null)
            {
                var mesaj = "Poliklinik Zaten Kayıtlı";
                ViewBag.deger = mesaj;
                return RedirectToAction("PoliklinikIndex");
            }
            var pol = _databaseContext.AnaBilimDallari.Where(x => x.Id == p.AnaBilimDali.Id).FirstOrDefault();
            p.AnaBilimDali = pol;
            _databaseContext.Add(p);
            _databaseContext.SaveChanges();

            return RedirectToAction("PoliklinikIndex");
        }
        public IActionResult PoliklinikSil(Guid id)
        {
            var silinecek = _databaseContext.Poliklinikler.FirstOrDefault(abd => abd.Id ==id);
            if (silinecek != null)
            {
                _databaseContext.Poliklinikler.Remove(silinecek);
                _databaseContext.SaveChanges();
            }
            return RedirectToAction("PoliklinikIndex");
        }

        public IActionResult PoliklinikGetir(Guid id)
        {
            var pol = _databaseContext.Poliklinikler.FirstOrDefault(pol => pol.Id == id);

            return View(pol);
        }

        public IActionResult PoliklinikGuncelle(Poliklinik pol)
        {
            var poliklinik_1 = _databaseContext.Poliklinikler.FirstOrDefault(abd => abd.Id == pol.Id);

            poliklinik_1.Name = pol.Name;
            _databaseContext.SaveChanges();
            return RedirectToAction("PoliklinikIndex");
        }
        public IActionResult DoktorIndex()
        {
            var doktorlar = _databaseContext.Doktorlar.Include(x => x.poliklinik).ToList();
            return View(doktorlar);
        }
        public IActionResult YeniDoktor()
        {

            List<SelectListItem> Pol = (from x in _databaseContext.Poliklinikler.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Name,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.dgr = Pol;
            return View();
        }
        [HttpPost]
        public IActionResult YeniDoktor(Doktor d)
        {

            var doc = _databaseContext.Poliklinikler.Where(x => x.Id == d.poliklinik.Id).FirstOrDefault();
            d.poliklinik = doc;
            _databaseContext.Add(d);
            _databaseContext.SaveChanges();

            return RedirectToAction("DoktorIndex");
        }

        public IActionResult DoktorSil(Guid id)
        {
            var silinecek = _databaseContext.Doktorlar.FirstOrDefault(doc => doc.Id == id);
            if (silinecek != null)
            {
                _databaseContext.Doktorlar.Remove(silinecek);
                _databaseContext.SaveChanges();
            }
            return RedirectToAction("DoktorIndex");
        }

        public IActionResult DoktorGetir(Guid id)
        {
            var doc = _databaseContext.Doktorlar.FirstOrDefault(doc => doc.Id == id);

            return View(doc);
        }
        public IActionResult DoktorGuncelle(Doktor doc)
        {
            var docc = _databaseContext.Doktorlar.FirstOrDefault(abd => abd.Id == doc.Id);

            docc.Name = doc.Name;
            _databaseContext.SaveChanges();
            return RedirectToAction("DoktorIndex");
        }

        public IActionResult KullaniciIndex()
        {
            var kullanicilar = _databaseContext.Users.ToList();
            return View(kullanicilar);
        }
        public IActionResult KullaniciSil(Guid id)
        {
            var silinecek = _databaseContext.Users.FirstOrDefault(abd => abd.UserID == id);

            _databaseContext.Users.Remove(silinecek);
            _databaseContext.SaveChanges();
            return RedirectToAction("KullaniciIndex");
        }
        public IActionResult KullaniciGetir(Guid id)
        {
            var usr = _databaseContext.Users.FirstOrDefault(abd => abd.UserID == id);

            return View(usr);
        }
        public IActionResult KullaniciGuncelle(User user)
        {
            var usr = _databaseContext.Users.FirstOrDefault(abd => abd.UserID == user.UserID);

            usr.Name = user.Name;
            usr.Surname = user.Surname;
            _databaseContext.SaveChanges();
            return RedirectToAction("KullaniciIndex");
        }

        public IActionResult RandevuIndex()
        {
            var userAppointments = _databaseContext.Randevular
            .Select(r => new RandevularımViewModel
            {
                Id = r.Id,
                AnabilimdaliName = _databaseContext.AnaBilimDallari.FirstOrDefault(a => a.Id == r.AnaBilimDaliId).Name,
                DoktorName = _databaseContext.Doktorlar.FirstOrDefault(d => d.Id == r.DoktorId).Name,
                PoliklinikName = _databaseContext.Poliklinikler.FirstOrDefault(p => p.Id == r.PoliklinikId).Name,
                RandevuDate = r.RandevuTarihi


            })
            .ToList();
            return View(userAppointments);


        }
        public IActionResult RandevuSil(Guid id)
        {

            var silinecek = _databaseContext.Randevular.FirstOrDefault(abd => abd.Id == id);

            _databaseContext.Randevular.Remove(silinecek);
            _databaseContext.SaveChanges();
            return RedirectToAction("RandevuIndex");

        }
    }
}

 

Hastane/Controllers/HesapController.cs
using System;

using Hastane.Models;
using Microsoft.AspNetCore.Mvc;
using NETCore.Encrypt.Extensions;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.DataAnnotations;
using Hastane.Entities;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Hastane.Controllers
{
    
    public class HesapController : Controller
    {
        private readonly ApplicationDbContext _databaseContext;
        private readonly IConfiguration _configuration;

        public HesapController(ApplicationDbContext databaseContext, IConfiguration configuration)
        {
            _databaseContext = databaseContext;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                string hashedPassword = DoMD5HashedString(model.Password);

                User user = _databaseContext.Users.SingleOrDefault(x => x.Username.ToLower() == model.Username.ToLower() && x.Password == hashedPassword);

                if (user != null)
                {
                    if (user.Locked)
                    {
                        ModelState.AddModelError(nameof(model.Username), "User is locked.");
                        return View(model);
                    }

                    List<Claim> claims = new List<Claim>();
                    claims.Add(new Claim(ClaimTypes.NameIdentifier, user.UserID.ToString()));
                    claims.Add(new Claim(ClaimTypes.Name, user.Name ?? string.Empty));
                    claims.Add(new Claim(ClaimTypes.Role, user.Role));
                    claims.Add(new Claim("Username", user.Username));

                    ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                 
                        return RedirectToAction("Index", "Home");
                    
                   
                }
                else
                {
                    ModelState.AddModelError("", "Username or password is incorrect.");
                }
            }
            return View(model);

        }
        public IActionResult Register()
        {
            return View();
        }

        private string DoMD5HashedString(string s)
        {
            string md5Salt = _configuration.GetValue<string>("AppSettings:MD5Salt");
            string salted = s + md5Salt;
            string hashed = salted.MD5();
            return hashed;
        }

        [HttpPost]
        public IActionResult Register(RegisterViewModel model)
        {



            if (ModelState.IsValid)
            {

                if (_databaseContext.Users.Any(x => x.Username.ToLower() == model.Username.ToLower()))
                {
                    ModelState.AddModelError(nameof(model.Username), "Username is already exists.");
                    View(model);
                }
                string hashedPassword = DoMD5HashedString(model.Password);
                User user = new()
                {
                    Username = model.Username,
                    Name = model.Name,
                    Surname = model.Surname,
                    Password = hashedPassword,

                };
                _databaseContext.Users.Add(user);
                int affectedRowCount = _databaseContext.SaveChanges();

                if (affectedRowCount == 0)
                {
                    ModelState.AddModelError("", "User can not be added.");
                }
                else
                {
                    return RedirectToAction(nameof(Login));
                }
            }
            return View(model);
            
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Login));
        }





    }
}

Hastane/Controllers/RandevuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Hastane.Entities;
using Hastane.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Hastane.Controllers
{
    [Authorize]
    public class RandevuController : Controller
    {

        private readonly ApplicationDbContext _databaseContext;

        public RandevuController(ApplicationDbContext databaseContext)
        {
            _databaseContext = databaseContext;

        }
        public IActionResult RandevuAl()
        {
            SelectList anabilim = new SelectList(_databaseContext.AnaBilimDallari, "Id", "Name");
            RandevuAlViewModel model = new RandevuAlViewModel()
            {

                AnaBilimDallari = anabilim,

                // Başlangıçta şehir verisi yoktur ama kayıt düzenleme yaparsanız burayı da doldurunuz.
                Poliklinikler = new SelectList(new List<Poliklinik>()),
                Doktorlar = new SelectList(new List<Doktor>())
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult RandevuAl(RandevuAlViewModel model)
        {
            // Model içinde gönderdiğimiz citiesData ve countriesData verileri View'dan alınmaz.
            // POST işlemi sonrasında aynı sayfa tekrar açılacak ise, 
            // Model e  değerlerini tekrar yüklemeliyiz. 
            // Bu verileri bir Cache mekanizmasından yükleyerek sürekli DB ye gitme gerekliliği kaldırabilirsiniz.
            // Performans açısından da daha doğru olacaktır. Tabii veriler sürekli değişmiyorsa..!
            SelectList AnaBilimDallarii = new SelectList(_databaseContext.AnaBilimDallari, "Id", "Name");
            SelectList Polikliniklerr = new SelectList(_databaseContext.Poliklinikler, "Id", "Name");
            SelectList Doktorlarr = new SelectList(_databaseContext.Doktorlar, "Id", "Name");
            var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            Randevu randevu = new()
            {
                AnaBilimDaliId = model.SelectedAnaBilimDaliId,
                PoliklinikId = model.SelectedPoliklinikId,
                DoktorId = model.SelectedDoktorId,
                RandevuTarihi = model.RandevuTarihi,
                UserId =userId
               
            };

            _databaseContext.Randevular.Add(randevu);
            _databaseContext.SaveChanges();

            model.AnaBilimDallari = AnaBilimDallarii;
            model.Poliklinikler = Polikliniklerr;
            model.Doktorlar = Doktorlarr;

            return View(model);
        }
        public JsonResult GetCitiesByCountry(Guid id)
        {
            return Json(
                _databaseContext.Poliklinikler.Where(ci => ci.AnaBilimDaliId == id).ToList());
        }
        public JsonResult GetCitiesByCountr(Guid id)
        {
            return Json(
                _databaseContext.Doktorlar.Where(ci => ci.PoliklinikId == id).ToList());
        }


        public IActionResult Randevularım()
            {
            var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
           

            var userAppointments = _databaseContext.Randevular
            .Where(r => r.UserId == userId) // Kullanıcıya ait randevuları filtrele
            .Select(r => new RandevularımViewModel
            {
                Id = r.Id,
                AnabilimdaliName = _databaseContext.AnaBilimDallari.FirstOrDefault(a => a.Id == r.AnaBilimDaliId).Name,
                DoktorName = _databaseContext.Doktorlar.FirstOrDefault(d => d.Id == r.DoktorId).Name,
                PoliklinikName = _databaseContext.Poliklinikler.FirstOrDefault(p => p.Id == r.PoliklinikId).Name,
                RandevuDate = r.RandevuTarihi
                
                
            })
            .ToList();


            return View(userAppointments);
            }
          public IActionResult RandevuSil(Guid id)
         {
            
            var silinecek = _databaseContext.Randevular.FirstOrDefault(abd => abd.Id == id);

            _databaseContext.Randevular.Remove(silinecek);
            _databaseContext.SaveChanges();
            return RedirectToAction("Randevularım");
            
         }

    }

}

Hastane/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hastane</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hastane.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MedLife</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Gizlilik</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                                    Languages
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a asp-controller="Home" asp-action="DilDegistir" asp-route-culture="en-US"
                                           class="dropdown-item">
                                            <i class="flag-icon flag-icon-gb"></i> English
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Home" asp-action="DilDegistir" asp-route-culture="tr-TR"
                                           class="dropdown-item">
                                            <i class="flag-icon flag-icon-gb"></i> Türkçe
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                            @if (User.Identity.IsAuthenticated)
                            {

                                @if (User.IsInRole("user"))
                                {
                                <li class="nav-item ms-auto">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Randevu" asp-action="Randevularım">
                                        <i class="fa-solid fa-user me-2"></i> Randevularım
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Randevu" asp-action="RandevuAl"><i class="fa-solid fa-right-from-bracket me-2"></i>Randevu Al</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Hesap" asp-action="Logout"><i class="fa-solid fa-right-from-bracket me-2"></i>Çıkış Yap</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item ms-auto">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index"><i class="fa-solid fa-right-from-bracket me-2"></i>Yönetici Paneli</a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Hesap" asp-action="Logout"><i class="fa-solid fa-right-from-bracket me-2"></i>Çıkış Yap</a>
                                </li>
                            }


                            }
                            else
                            {

                                <li class="nav-item ms-auto">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Hesap" asp-action="Login"><i class="fa-solid fa-right-to-bracket me-2"></i>Giriş Yap</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Hesap" asp-action="Register"><i class="fa-solid fa-user me-2"></i>Kayıt Yap</a>
                                </li>
                            }
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MedLife - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Hastane/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>

    <title>Admin</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/Hastane.styles.css" asp-append-version="true" />
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">İşlemler</h3>
        <a href="/Admin/index" class="w3-bar-item w3-button">Ana Bilim Dalları</a>
        <a href="/Admin/PoliklinikIndex" class="w3-bar-item w3-button">Poliklinikler</a>
        <a href="/Admin/DoktorIndex" class="w3-bar-item w3-button">Doktorlar</a>
        <a href="/Admin/KullaniciIndex" class="w3-bar-item w3-button">Kullanıcılar</a>
        <a href="/Admin/RandevuIndex" class="w3-bar-item w3-button">Randevular</a>

        <a class="nav-link text-dark" asp-area="" asp-controller="Hesap" asp-action="Logout"><i class="fa-solid fa-right-from-bracket me-2"></i>Çıkış Yap</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h1>MedLife</h1>
        </div>



        <div class="w3-container">
            @RenderBody()
        </div>

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
    
</html>